// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mineplex.FinPlanner.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mineplex.FinPlanner.Api.Migrations
{
    [DbContext(typeof(FinPlannerDbContext))]
    [Migration("20260125050604_AddRentalGrowth")]
    partial class AddRentalGrowth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.AIRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AIRecommendations");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Market")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("AssetCategories");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.AssetPriceSourceOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomSymbol")
                        .HasColumnType("text");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PriceSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestedSymbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PriceSourceId");

                    b.ToTable("AssetPriceSourceOverrides");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.CommercialProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProxyAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleReference")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalGFA")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProxyAssetId");

                    b.ToTable("CommercialProperties");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.CurrentPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("SourceUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("LastUpdated");

                    b.ToTable("CurrentPrices");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.DealSimulationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedCapRate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<string>("IRRHistogramJson")
                        .HasColumnType("text");

                    b.Property<string>("InputsSnapshotJson")
                        .HasColumnType("text");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<decimal>("MedianIRR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedianNPV")
                        .HasColumnType("numeric");

                    b.Property<string>("NPVHistogramJson")
                        .HasColumnType("text");

                    b.Property<decimal>("P10IRR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("P10NPV")
                        .HasColumnType("numeric");

                    b.Property<decimal>("P90IRR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("P90NPV")
                        .HasColumnType("numeric");

                    b.Property<string>("RecommendedDecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YearlyDCFJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("DealSimulationResults");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllocationMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FileUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ImplementedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ProjectedTaxImpact")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotAfter")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SnapshotBefore")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileUploadId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.DecisionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("DecisionLogs");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.FileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyDealId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ValuationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("PropertyDealId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("FileUploads");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.HistoricalPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Date")
                        .IsUnique();

                    b.ToTable("HistoricalPrices");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.ImportedAssetPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileUploadId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("ValuationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileUploadId");

                    b.HasIndex("AssetId", "ValuationDate");

                    b.ToTable("ImportedAssetPrices");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.LeaseProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GLA")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LeaseEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LeaseStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OptionPeriod")
                        .HasColumnType("text");

                    b.Property<decimal>("OutgoingsRecoverable")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ReviewPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeaseEnd");

                    b.HasIndex("PropertyId");

                    b.ToTable("LeaseProfiles");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllocationBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PerformanceSnapshots");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BenchmarkAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetAllocation")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkAssetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PriceSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Priority");

                    b.ToTable("PriceSources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "YAHOO",
                            IsEnabled = true,
                            Name = "Yahoo Finance",
                            Priority = 1,
                            RateLimitPerMinute = 2000
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "MORNINGSTAR_AU",
                            IsEnabled = true,
                            Name = "Morningstar Australia",
                            Priority = 2,
                            RateLimitPerMinute = 120
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "ALPHAVANTAGE",
                            IsEnabled = false,
                            Name = "Alpha Vantage",
                            Priority = 3,
                            RateLimitPerMinute = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "POLYGON",
                            IsEnabled = false,
                            Name = "Polygon.io",
                            Priority = 4,
                            RateLimitPerMinute = 5
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "IMPORTED",
                            IsEnabled = true,
                            Name = "Imported File",
                            Priority = 10,
                            RateLimitPerMinute = 10000
                        });
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PropertyDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcquiredAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal>("AskingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("BuildingType")
                        .HasColumnType("text");

                    b.Property<decimal>("CapExReserve")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CapitalGrowthPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CapitalGrowthVariancePercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionRationale")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedGrossRent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("numeric");

                    b.Property<int>("HoldingPeriodYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestRatePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InterestVariancePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("LeaseDetailsJson")
                        .HasColumnType("text");

                    b.Property<decimal>("LegalCosts")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("LoanDetailsJson")
                        .HasColumnType("text");

                    b.Property<int>("LoanTermYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("ManagementFeePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OutgoingsEstimate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RentVariancePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RentalGrowthPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("SpreadsheetOverridesJson")
                        .HasColumnType("text");

                    b.Property<decimal>("StampDutyRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VacancyRatePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VacancyVariancePercent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PropertyDeals");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PropertyLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FileUploadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileUploadId");

                    b.HasIndex("PropertyId", "Date");

                    b.ToTable("PropertyLedgerEntries");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PropertyValuation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Date");

                    b.ToTable("PropertyValuations");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "PriceUpdateIntervalMinutes",
                            Description = "How often to update market prices (in minutes)",
                            LastModified = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "15"
                        });
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.TaxParcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquisitionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingUnits")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("TaxParcels");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttachedOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReferenceId")
                        .HasColumnType("text");

                    b.Property<Guid?>("FileUploadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("FileUploadId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleSubjectId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.AIRecommendation", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Account", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.AssetCategory", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.AssetPriceSourceOverride", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.PriceSource", "PriceSource")
                        .WithMany()
                        .HasForeignKey("PriceSourceId");

                    b.Navigation("Asset");

                    b.Navigation("PriceSource");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.CommercialProperty", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "ProxyAsset")
                        .WithMany()
                        .HasForeignKey("ProxyAssetId");

                    b.Navigation("Owner");

                    b.Navigation("ProxyAsset");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.CurrentPrice", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithOne("CurrentPrice")
                        .HasForeignKey("Mineplex.FinPlanner.Api.Models.CurrentPrice", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.DealSimulationResult", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.PropertyDeal", "Deal")
                        .WithMany("SimulationResults")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Decision", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.FileUpload", "FileUpload")
                        .WithMany()
                        .HasForeignKey("FileUploadId");

                    b.HasOne("Mineplex.FinPlanner.Api.Models.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileUpload");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.FileUpload", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Mineplex.FinPlanner.Api.Models.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.PropertyDeal", "PropertyDeal")
                        .WithMany()
                        .HasForeignKey("PropertyDealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mineplex.FinPlanner.Api.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Portfolio");

                    b.Navigation("PropertyDeal");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.HistoricalPrice", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Holding", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.AssetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.ImportedAssetPrice", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.FileUpload", "FileUpload")
                        .WithMany()
                        .HasForeignKey("FileUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("FileUpload");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.LeaseProfile", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.CommercialProperty", "Property")
                        .WithMany("Leases")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PerformanceSnapshot", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Portfolio", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "BenchmarkAsset")
                        .WithMany()
                        .HasForeignKey("BenchmarkAssetId");

                    b.HasOne("Mineplex.FinPlanner.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkAsset");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PropertyLedger", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.FileUpload", "FileUpload")
                        .WithMany()
                        .HasForeignKey("FileUploadId");

                    b.HasOne("Mineplex.FinPlanner.Api.Models.CommercialProperty", "Property")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileUpload");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PropertyValuation", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.CommercialProperty", "Property")
                        .WithMany("Valuations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.TaxParcel", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Transaction", b =>
                {
                    b.HasOne("Mineplex.FinPlanner.Api.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mineplex.FinPlanner.Api.Models.FileUpload", "FileUpload")
                        .WithMany()
                        .HasForeignKey("FileUploadId");

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("FileUpload");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.Asset", b =>
                {
                    b.Navigation("CurrentPrice");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.CommercialProperty", b =>
                {
                    b.Navigation("Leases");

                    b.Navigation("LedgerEntries");

                    b.Navigation("Valuations");
                });

            modelBuilder.Entity("Mineplex.FinPlanner.Api.Models.PropertyDeal", b =>
                {
                    b.Navigation("SimulationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
